#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1";  IMAGE="dokku/$APP"

NPMSCRIPT="
#!/bin/bash

cd /app
PATH=\$PATH:/app/vendor/node/bin
if [[ -f ./package.json ]]; then
	npm install
fi
"

echo '-----> Injecting node script'
id=$(echo "$NPMSCRIPT" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > /app/.nodejs")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
id=$(docker run -d $IMAGE /bin/bash -c "chmod +x /app/.nodejs")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
