#!/bin/bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1";  IMAGE="dokku/$APP"

echo "-----> Injecting Node & Packages ..."

build_dir = "/app"
node_version="0.10.18"
node_url="http://s3pository.heroku.com/node/v$node_version/node-v$node_version-linux-x64.tar.gz"

COMMAND=$(cat <<EOF
# Download node from Heroku's S3 mirror of nodejs.org/dist
curl $node_url -s -o - | tar xzf - -C $build_dir

# Move node (and npm) into ./vendor and make them executable
mkdir -p $build_dir/vendor
mv $build_dir/node-v$node_version-linux-x64 $build_dir/vendor/node
chmod +x $build_dir/vendor/node/bin/*
PATH=$build_dir/vendor/node/bin:$PATH

# Run subsequent node/npm commands from the build path
cd $build_dir
npm install --userconfig $build_dir/.npmrc --production 2>&1

# Update the PATH
mkdir -p $build_dir/.profile.d
echo "export PATH=\"\$build_dir/vendor/node/bin:\$build_dir/bin:\$build_dir/node_modules/.bin:\$PATH\";" > $build_dir/.profile.d/nodejs.sh

EOF
)

id=$(docker run -d $IMAGE /bin/bash -c "$COMMAND")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
